### ISSUE TITLE
Presentation

### ISSUE THREAD

**Issue by albertosuarez8** [albertosuarez8/Venue-Views#13]

**Comment by jujubea22** [comment]
Power point would not load hopefully this you could see 
[vVenue Views.pdf](https://github.com/albertosuarez8/Venue-Views/files/10473791/vVenue.Views.pdf)

**Comment by jujubea22** [comment]
Edit the power point to the new look tomorrow Morning :)

**Comment by jujubea22** [comment]
https://www.canva.com/design/DAFYiF4Fcp0/XOV0Q1zQ_d_g2Fe5Jl6F_w/edit?utm_content=DAFYiF4Fcp0&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton
