### ISSUE TITLE
CSS Styling

### ISSUE THREAD

**Issue by albertosuarez8** [albertosuarez8/Venue-Views#20]

**Comment by laps22** [comment]
Using CSS framework Bulma.

**Comment by albertosuarez8** [comment]
{{#each posts as |post|}}
    <img src="{{post.image}}"></img>
    {{post.description}}
    {{format_time post.date}}
    {{post.rating}}
    {{post.user.name}
{{/each}}

**Comment by albertosuarez8** [comment]
post.user.name doesn't work in the user dashboard. it is for the home page or if a user searches that brewery
